export * from "./login"
export * from "./role"
export * from "./permissions"
export * from "./departamento"
export * from "./bank"
export * from "./coin"
export * from "./sucursal"
export * from "./departamento"
export * from "./minicipio"
export * from "./rolPermiso"
export * from "./categoria"

