import type { Metadata } from "next";
import { AppSidebar, Navbar } from "@/components";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Navbar />
        <div className="">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}