import type { Metadata } from "next";
import { AppSidebar, Navbar } from "@/components";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="justify-end">
        <Navbar />
        {children}
      </main>
    </SidebarProvider>
  );
}
